# coding: utf-8

"""
    Python SDK for Opsgenie REST API

    Python SDK for Opsgenie REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@opsgenie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AddResponderToAlertPayloadAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'responder': 'Recipient'
    }

    attribute_map = {
        'responder': 'responder'
    }

    def __init__(self, responder=None):  # noqa: E501
        """AddResponderToAlertPayloadAllOf - a model defined in OpenAPI"""  # noqa: E501

        self._responder = None
        self.discriminator = None

        self.responder = responder

    @property
    def responder(self):
        """Gets the responder of this AddResponderToAlertPayloadAllOf.  # noqa: E501


        :return: The responder of this AddResponderToAlertPayloadAllOf.  # noqa: E501
        :rtype: Recipient
        """
        return self._responder

    @responder.setter
    def responder(self, responder):
        """Sets the responder of this AddResponderToAlertPayloadAllOf.


        :param responder: The responder of this AddResponderToAlertPayloadAllOf.  # noqa: E501
        :type: Recipient
        """
        if responder is None:
            raise ValueError("Invalid value for `responder`, must not be `None`")  # noqa: E501

        self._responder = responder

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddResponderToAlertPayloadAllOf):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
