# coding: utf-8

"""
    Python SDK for Opsgenie REST API

    Python SDK for Opsgenie REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@opsgenie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SavedSearch(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'owner': 'SavedSearchEntity',
        'teams': 'list[SavedSearchEntity]',
        'description': 'str',
        'query': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'owner': 'owner',
        'teams': 'teams',
        'description': 'description',
        'query': 'query'
    }

    def __init__(self, id=None, name=None, created_at=None, updated_at=None, owner=None, teams=None, description=None, query=None):  # noqa: E501
        """SavedSearch - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._created_at = None
        self._updated_at = None
        self._owner = None
        self._teams = None
        self._description = None
        self._query = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if owner is not None:
            self.owner = owner
        if teams is not None:
            self.teams = teams
        if description is not None:
            self.description = description
        if query is not None:
            self.query = query

    @property
    def id(self):
        """Gets the id of this SavedSearch.  # noqa: E501


        :return: The id of this SavedSearch.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SavedSearch.


        :param id: The id of this SavedSearch.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SavedSearch.  # noqa: E501


        :return: The name of this SavedSearch.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SavedSearch.


        :param name: The name of this SavedSearch.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def created_at(self):
        """Gets the created_at of this SavedSearch.  # noqa: E501


        :return: The created_at of this SavedSearch.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SavedSearch.


        :param created_at: The created_at of this SavedSearch.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this SavedSearch.  # noqa: E501


        :return: The updated_at of this SavedSearch.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this SavedSearch.


        :param updated_at: The updated_at of this SavedSearch.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def owner(self):
        """Gets the owner of this SavedSearch.  # noqa: E501


        :return: The owner of this SavedSearch.  # noqa: E501
        :rtype: SavedSearchEntity
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this SavedSearch.


        :param owner: The owner of this SavedSearch.  # noqa: E501
        :type: SavedSearchEntity
        """

        self._owner = owner

    @property
    def teams(self):
        """Gets the teams of this SavedSearch.  # noqa: E501


        :return: The teams of this SavedSearch.  # noqa: E501
        :rtype: list[SavedSearchEntity]
        """
        return self._teams

    @teams.setter
    def teams(self, teams):
        """Sets the teams of this SavedSearch.


        :param teams: The teams of this SavedSearch.  # noqa: E501
        :type: list[SavedSearchEntity]
        """

        self._teams = teams

    @property
    def description(self):
        """Gets the description of this SavedSearch.  # noqa: E501


        :return: The description of this SavedSearch.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SavedSearch.


        :param description: The description of this SavedSearch.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def query(self):
        """Gets the query of this SavedSearch.  # noqa: E501


        :return: The query of this SavedSearch.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this SavedSearch.


        :param query: The query of this SavedSearch.  # noqa: E501
        :type: str
        """

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SavedSearch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
