# coding: utf-8

"""
    Python SDK for Opsgenie REST API

    Python SDK for Opsgenie REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@opsgenie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class HeartbeatMeta(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'enabled': 'bool',
        'expired': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'enabled': 'enabled',
        'expired': 'expired'
    }

    def __init__(self, name=None, enabled=None, expired=None):  # noqa: E501
        """HeartbeatMeta - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._enabled = None
        self._expired = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if enabled is not None:
            self.enabled = enabled
        if expired is not None:
            self.expired = expired

    @property
    def name(self):
        """Gets the name of this HeartbeatMeta.  # noqa: E501


        :return: The name of this HeartbeatMeta.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HeartbeatMeta.


        :param name: The name of this HeartbeatMeta.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def enabled(self):
        """Gets the enabled of this HeartbeatMeta.  # noqa: E501


        :return: The enabled of this HeartbeatMeta.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this HeartbeatMeta.


        :param enabled: The enabled of this HeartbeatMeta.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def expired(self):
        """Gets the expired of this HeartbeatMeta.  # noqa: E501


        :return: The expired of this HeartbeatMeta.  # noqa: E501
        :rtype: bool
        """
        return self._expired

    @expired.setter
    def expired(self, expired):
        """Sets the expired of this HeartbeatMeta.


        :param expired: The expired of this HeartbeatMeta.  # noqa: E501
        :type: bool
        """

        self._expired = expired

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HeartbeatMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
