# coding: utf-8

"""
    OpsGenie REST API

    OpsGenie API Description

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat

from six import iteritems


class AlertReport(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self, ack_time=None, close_time=None, acknowledged_by=None, closed_by=None):
        """
        AlertReport - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ack_time': 'int',
            'close_time': 'int',
            'acknowledged_by': 'str',
            'closed_by': 'str'
        }

        self.attribute_map = {
            'ack_time': 'ackTime',
            'close_time': 'closeTime',
            'acknowledged_by': 'acknowledgedBy',
            'closed_by': 'closedBy'
        }

        self._ack_time = ack_time
        self._close_time = close_time
        self._acknowledged_by = acknowledged_by
        self._closed_by = closed_by

    @property
    def ack_time(self):
        """
        Gets the ack_time of this AlertReport.

        :return: The ack_time of this AlertReport.
        :rtype: int
        """
        return self._ack_time

    @ack_time.setter
    def ack_time(self, ack_time):
        """
        Sets the ack_time of this AlertReport.

        :param ack_time: The ack_time of this AlertReport.
        :type: int
        """

        self._ack_time = ack_time

    @property
    def close_time(self):
        """
        Gets the close_time of this AlertReport.

        :return: The close_time of this AlertReport.
        :rtype: int
        """
        return self._close_time

    @close_time.setter
    def close_time(self, close_time):
        """
        Sets the close_time of this AlertReport.

        :param close_time: The close_time of this AlertReport.
        :type: int
        """

        self._close_time = close_time

    @property
    def acknowledged_by(self):
        """
        Gets the acknowledged_by of this AlertReport.

        :return: The acknowledged_by of this AlertReport.
        :rtype: str
        """
        return self._acknowledged_by

    @acknowledged_by.setter
    def acknowledged_by(self, acknowledged_by):
        """
        Sets the acknowledged_by of this AlertReport.

        :param acknowledged_by: The acknowledged_by of this AlertReport.
        :type: str
        """

        self._acknowledged_by = acknowledged_by

    @property
    def closed_by(self):
        """
        Gets the closed_by of this AlertReport.

        :return: The closed_by of this AlertReport.
        :rtype: str
        """
        return self._closed_by

    @closed_by.setter
    def closed_by(self, closed_by):
        """
        Sets the closed_by of this AlertReport.

        :param closed_by: The closed_by of this AlertReport.
        :type: str
        """

        self._closed_by = closed_by

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AlertReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
