# coding: utf-8

"""
    Python SDK for Opsgenie REST API

    Python SDK for Opsgenie REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@opsgenie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PageDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'prev': 'str',
        'next': 'str',
        'first': 'str',
        'last': 'str'
    }

    attribute_map = {
        'prev': 'prev',
        'next': 'next',
        'first': 'first',
        'last': 'last'
    }

    def __init__(self, prev=None, next=None, first=None, last=None):  # noqa: E501
        """PageDetails - a model defined in OpenAPI"""  # noqa: E501

        self._prev = None
        self._next = None
        self._first = None
        self._last = None
        self.discriminator = None

        if prev is not None:
            self.prev = prev
        if next is not None:
            self.next = next
        if first is not None:
            self.first = first
        if last is not None:
            self.last = last

    @property
    def prev(self):
        """Gets the prev of this PageDetails.  # noqa: E501


        :return: The prev of this PageDetails.  # noqa: E501
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this PageDetails.


        :param prev: The prev of this PageDetails.  # noqa: E501
        :type: str
        """

        self._prev = prev

    @property
    def next(self):
        """Gets the next of this PageDetails.  # noqa: E501


        :return: The next of this PageDetails.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this PageDetails.


        :param next: The next of this PageDetails.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def first(self):
        """Gets the first of this PageDetails.  # noqa: E501


        :return: The first of this PageDetails.  # noqa: E501
        :rtype: str
        """
        return self._first

    @first.setter
    def first(self, first):
        """Sets the first of this PageDetails.


        :param first: The first of this PageDetails.  # noqa: E501
        :type: str
        """

        self._first = first

    @property
    def last(self):
        """Gets the last of this PageDetails.  # noqa: E501


        :return: The last of this PageDetails.  # noqa: E501
        :rtype: str
        """
        return self._last

    @last.setter
    def last(self, last):
        """Sets the last of this PageDetails.


        :param last: The last of this PageDetails.  # noqa: E501
        :type: str
        """

        self._last = last

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PageDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
