# coding: utf-8

"""
    Python SDK for Opsgenie REST API

    Python SDK for Opsgenie REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@opsgenie.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class StatusPageEntry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'title': 'str',
        'details': 'str'
    }

    attribute_map = {
        'title': 'title',
        'details': 'details'
    }

    def __init__(self, title=None, details=None):  # noqa: E501
        """StatusPageEntry - a model defined in OpenAPI"""  # noqa: E501

        self._title = None
        self._details = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if details is not None:
            self.details = details

    @property
    def title(self):
        """Gets the title of this StatusPageEntry.  # noqa: E501

        The message to be added using status page into incident  # noqa: E501

        :return: The title of this StatusPageEntry.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this StatusPageEntry.

        The message to be added using status page into incident  # noqa: E501

        :param title: The title of this StatusPageEntry.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def details(self):
        """Gets the details of this StatusPageEntry.  # noqa: E501

        Description of the message being added via stats page into incident  # noqa: E501

        :return: The details of this StatusPageEntry.  # noqa: E501
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this StatusPageEntry.

        Description of the message being added via stats page into incident  # noqa: E501

        :param details: The details of this StatusPageEntry.  # noqa: E501
        :type: str
        """

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StatusPageEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
